"""create loan_application table

Revision ID: 6580c0f5e765
Revises: 
Create Date: 2025-04-30 23:13:33.129250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6580c0f5e765'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_application',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
                    sa.Column('term_months', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_loan_application_id'), 'loan_application', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_application_id'), table_name='loan_application')
    op.drop_table('loan_application')
    # ### end Alembic commands ###
