"""init credit score report

Revision ID: 7a8975d7d14d
Revises: 
Create Date: 2025-05-12 02:18:10.037321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7a8975d7d14d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_score_report',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.Column('source', sa.String(length=50), nullable=False),
                    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_score_report')
    # ### end Alembic commands ###