"""init

Revision ID: 1771ca4d7d80
Revises: 
Create Date: 2025-05-10 21:38:45.696112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1771ca4d7d80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.Column('dob', sa.Date(), nullable=False),
                    sa.Column('national_id', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('user_account_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_index(op.f('ix_customer_user_account_id'), 'customer', ['user_account_id'], unique=False)
    op.create_table('credit_status',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('current_score', sa.Integer(), nullable=False),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_credit_status_id'), 'credit_status', ['id'], unique=False)
    op.create_table('financial_profile',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('income', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('employment_status', sa.String(length=50), nullable=False),
                    sa.Column('debts', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('assets', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_financial_profile_id'), 'financial_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_profile_id'), table_name='financial_profile')
    op.drop_table('financial_profile')
    op.drop_index(op.f('ix_credit_status_id'), table_name='credit_status')
    op.drop_table('credit_status')
    op.drop_index(op.f('ix_customer_user_account_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###