"""change date

Revision ID: 75f2d0ef60d8
Revises: 1771ca4d7d80
Create Date: 2025-05-11 01:38:48.757050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f2d0ef60d8'
down_revision: Union[str, None] = '1771ca4d7d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'dob',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'dob',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###